version: '3.7'

services:
  galette:
    image: galette/galette:<version>
    container_name: galette
    stdin_open: true
    tty: true
    environment:
      - TZ=Europe/Paris # Define Timezone. Europe/Paris by default.
      - RM_INSTALL_FOLDER=0 # 0 by default. Turn to "1" to remove "install" folder (for security purpose), after installation/update.    
    ports:
      - 8080:80
    volumes:
      - ./data/attachments:/var/www/galette/data/attachments
      - ./data/cache:/var/www/galette/data/cache
#      - ./data/exports:/var/www/galette/data/exports
      - ./data/files:/var/www/galette/data/files
#      - ./data/logs:/var/www/galette/data/logs
      - ./data/photos:/var/www/galette/data/photos
#      - ./data/tempimages:/var/www/galette/data/tempimages
#      - ./data/template_c:/var/www/galette/data/template_c
      - ./data/templates_c:/var/www/galette/data/templates_c
# Uncomment this line below, after you have launch once Galette to create database : see file config / config.inc.php
#      - ./config/config.inc.php:/var/www/galette/config/config.inc.php
# Uncomment this line below, to Log IP addresses behind a proxy or enabling debug mode : see file config/behavior.inc.php
# https://doc.galette.eu/en/master/usermanual/avancee.html#log-ip-addresses-behind-a-proxy
#      - ./config/behavior.inc.php:/var/www/galette/config/behavior.inc.php
# Uncomment this line below, to enable a custom css
# https://doc.galette.eu/en/master/usermanual/avancee.html#adapt-to-your-graphical-chart
#      - ./galette_local.css:/var/www/galette/webroot/themes/default/galette_local.css
